name: binance_vwap_env
channels:
  - conda-forge
dependencies:
  - python=3.10.9
  - pandas=1.4.4
  - numpy=1.22.4
  - seaborn=0.12.1
  - matplotlib=3.6.2
  - numba=0.55.2
  - requests=2.28.1
  - scikit-learn=1.1.3
  - pip